import { TutorialSlides } from "@/schemas/onboarding.schema";

export const TUTORIAL_SLIDES: TutorialSlides = [
  {
    title: "Discover and Search for Stocks",
    description:
      "Explore trending stocks in the Discover section or search for your favorite companies to add to your portfolio.",
    videoSrc: "/videos/onboarding/discover.mp4",
  },
  {
    title: "Fine-Tune Your Portfolio",
    description:
      "Easily allocate weights to your stocks for a balanced and optimized portfolio.",
    videoSrc: "/videos/onboarding/optimize-weights.mp4",
  },
  {
    title: "Simulate Your Portfolio",
    description:
      "Run simulations to see how your portfolio would have performed historically.",
    videoSrc: "/videos/onboarding/simulate-portfolio.mp4",
  },
  {
    title: "Save Your Work",
    description: "Save your portfolios to revisit or tweak them anytime.",
    videoSrc: "/videos/onboarding/save-portfolio.mp4",
  },
  {
    title: "Share Your Success",
    description:
      "Share your portfolios with friends or the community and leverages AI to get feedback.",
    videoSrc: "/videos/onboarding/share-portfolio.mp4",
  },
  {
    title: "Try StockQuest AI",
    description:
      "Get personalized portfolio recommendations generated by our AI.",
    videoSrc: "/videos/onboarding/stockquest-ai.mp4",
  },
];
