import { z } from "zod";
import { DateSchema } from "./date.schema";

export const ScreenerQuoteSchema = z.object({
  language: z.string(),
  region: z.string(),
  quoteType: z.string(),
  typeDisp: z.string(),
  quoteSourceName: z.string().default("N/A"),
  triggerable: z.boolean().optional(),
  customPriceAlertConfidence: z.string().optional(),
  lastClosePriceToNNWCPerShare: z.number().optional(),
  exchange: z.string().default("N/A"),
  fiftyTwoWeekHigh: z.number().optional(),
  fiftyTwoWeekLow: z.number().optional(),
  averageAnalystRating: z.string().optional(),
  shortName: z.string().default("N/A"),
  currency: z.string().default("N/A"),
  hasPrePostMarketData: z.boolean().optional(),
  firstTradeDateMilliseconds: z.number().optional(),
  priceHint: z.number().optional(),
  preMarketChange: z.number().optional(),
  preMarketChangePercent: z.number().optional(),
  preMarketTime: z.number().optional(),
  preMarketPrice: z.number().optional(),
  regularMarketChange: z.number(),
  regularMarketTime: z.number(),
  regularMarketPrice: z.number(),
  regularMarketDayHigh: z.number(),
  regularMarketDayRange: z.any(),
  regularMarketDayLow: z.number(),
  regularMarketVolume: z.number(),
  regularMarketPreviousClose: z.number(),
  bid: z.number(),
  ask: z.number(),
  bidSize: z.number(),
  askSize: z.number(),
  market: z.string(),
  messageBoardId: z.string().optional(),
  fullExchangeName: z.string().default("N/A"),
  longName: z.string().default("N/A"),
  financialCurrency: z.string().default("N/A"),
  regularMarketOpen: z.number().optional(),
  averageDailyVolume3Month: z.number().optional(),
  averageDailyVolume10Day: z.number().optional(),
  corporateActions: z.array(z.unknown()).optional(),
  fiftyTwoWeekLowChange: z.number().optional(),
  fiftyTwoWeekLowChangePercent: z.number().optional(),
  fiftyTwoWeekRange: z.any(),
  fiftyTwoWeekHighChange: z.number().optional(),
  fiftyTwoWeekHighChangePercent: z.number().optional(),
  fiftyTwoWeekChangePercent: z.number().optional(),
  earningsTimestamp: z.number().optional(),
  earningsTimestampStart: z.number().optional(),
  earningsTimestampEnd: z.number().optional(),
  earningsCallTimestampStart: z.number().optional(),
  earningsCallTimestampEnd: z.number().optional(),
  isEarningsDateEstimate: z.boolean().optional(),
  trailingAnnualDividendRate: z.number().optional(),
  trailingAnnualDividendYield: z.number().optional(),
  marketState: z.string().optional(),
  priceEpsCurrentYear: z.number().optional(),
  sharesOutstanding: z.number(),
  bookValue: z.number().optional(),
  fiftyDayAverage: z.number().optional(),
  fiftyDayAverageChange: z.number().optional(),
  fiftyDayAverageChangePercent: z.number().optional(),
  twoHundredDayAverage: z.number().optional(),
  twoHundredDayAverageChange: z.number().optional(),
  twoHundredDayAverageChangePercent: z.number().optional(),
  marketCap: z.number(),
  forwardPE: z.number().optional(),
  priceToBook: z.number().optional(),
  sourceInterval: z.number().optional(),
  exchangeDataDelayedBy: z.number().optional(),
  exchangeTimezoneName: z.string().default("N/A"),
  exchangeTimezoneShortName: z.string().default("N/A"),
  gmtOffSetMilliseconds: z.number().optional(),
  prevName: z.string().optional(),
  nameChangeDate: DateSchema.optional(),
  esgPopulated: z.boolean().optional(),
  tradeable: z.boolean().optional(),
  cryptoTradeable: z.boolean().optional(),
  epsTrailingTwelveMonths: z.number().optional(),
  epsForward: z.number().optional(),
  epsCurrentYear: z.number().optional(),
  regularMarketChangePercent: z.number(),
  displayName: z.string().default("N/A"),
  symbol: z.string().default("N/A"),
});
export const ScreenerQuotesSchema = z.array(ScreenerQuoteSchema);

export type ScrennerQuote = z.infer<typeof ScreenerQuoteSchema>;
export type ScreenerQuotes = z.infer<typeof ScreenerQuotesSchema>;
